DROP TABLE IF EXISTS CAT;
CREATE TABLE CAT (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255),
    COLOR VARCHAR(255)
);

DROP TABLE IF EXISTS DOG;
CREATE TABLE DOG (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255),
    COLOR VARCHAR(255)
);
